### ISSUE TITLE
Example how to run on different hosts 

### ISSUE THREAD

**Issue by btilford** [ojongerius/terraform-provider-datadog#67]
Is there a way you can tell the datadog service check where to run? I'm trying to apply it to an AWS launch config. From the existing examples I'm not sure where it is creating the service check.

**Comment by ojongerius** [comment]
This plugin will create a _monitor_, but not a _service check_. By default it will monitor _all_ hosts that run a given service check.

So the flow would be: 

* Run service checks on host(s)
* Create monitors for those service checks using this plugin

You can filter for which hosts / groups alerts are generated by using [tags](http://docs.datadoghq.com/guides/tagging/).

If you think the documentation could be a little more clear I'd be happy to accept a PR :smile:

**Comment by btilford** [comment]
That makes a lot more sense.
