### ISSUE TITLE
Get provider merged in Terraform

### ISSUE THREAD

**Issue by ojongerius** [ojongerius/terraform-provider-datadog#75]
TODO:
* Fix build in [PR](https://github.com/hashicorp/terraform/pull/3611)
* Add documentation
* Make sure all boxes in [CONTRIBUTING.md](https://github.com/hashicorp/terraform/blob/master/CONTRIBUTING.md) are ticked

**Comment by ojongerius** [comment]
Build has been fixed, have added documentation, AFAICS all boxes have been ticked.

**Comment by jen20** [comment]
This is merged in Terraform and should be in 0.6.12 - it hit in hashicorp/terraform#5251.

**Comment by ojongerius** [comment]
Awesome, thanks @jen20!
